# Generated by Django 4.0.5 on 2023-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0002_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hobbie',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='strength',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
