# Generated by Django 4.0.5 on 2023-04-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0004_language_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description_html',
            field=models.TextField(editable=False, null=True),
        ),
    ]
