# Generated by Django 4.0.5 on 2023-04-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0005_skill_description_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description_html',
            field=models.TextField(null=True),
        ),
    ]
